# Generated by Django 2.2.24 on 2021-06-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Siji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cart', models.ForeignKey(on_delete='CASCADE', to='t01.Cart', verbose_name='车')),
            ],
        ),
    ]
